version: '3.8'

services:
  postDB:
    image: postgres:16.2
    restart: always
    container_name: diaryDatabase
    environment:
      POSTGRES_PASSWORD: masterkey
      POSTGRES_USER: admin
      PGDATA: /data/postgres
    volumes:
      - /var/lib/docker/volumes/diaryVol/_data
    ports:
      - "5433:5433"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: masterkey
    ports:
      - "5050:80"
